/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vjproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author mhm55
 */
public class Registr2Pharmacy extends javax.swing.JFrame {
    
    

    String db_query  = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registr2Pharmacy.class.getName());

    /**
     * Creates new form Registr2Pharmacy
     */
    public Registr2Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsertypeBG = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNametxt = new javax.swing.JTextField();
        userpasstxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustomerRB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        PharmcistRB = new javax.swing.JRadioButton();
        Sumbmetbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 3, 24)); // NOI18N
        jLabel1.setText("registration");

        jLabel3.setText("Name");

        jLabel4.setText("Password");

        UsertypeBG.add(CustomerRB);
        CustomerRB.setText("Customer");
        CustomerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerRBActionPerformed(evt);
            }
        });

        jLabel2.setText("Type");

        UsertypeBG.add(PharmcistRB);
        PharmcistRB.setText("Pharmcist");

        Sumbmetbtn.setText("Submet");
        Sumbmetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumbmetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CustomerRB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PharmcistRB))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(Sumbmetbtn)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerRB)
                    .addComponent(jLabel2)
                    .addComponent(PharmcistRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Sumbmetbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerRBActionPerformed

    private void SumbmetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumbmetbtnActionPerformed
        if(CustomerRB.isSelected()){
            try{    String name = userNametxt.getText();
                    String pass = userpasstxt.getText();
                    db_query = String.format("""
                                             INSERT INTO Customers(userName, userpass)
                                             Values('%s','%s');""",
                        name,pass );
                    Connection conn = Connection2DB.ConneectorDB();
                    Statement s = conn.createStatement();
                    s.executeUpdate(db_query);
                    JOptionPane.showMessageDialog(null,"Submetd!");
                    pharmacyLogin frm = new pharmacyLogin();
                    frm.setVisible(true);
                    this.dispose();

                }
                catch(SQLException sqle){
                    System.out.println(sqle.getMessage());
                }
        }
        else if(PharmcistRB.isSelected()){
            try{    String name = userNametxt.getText();
                    String pass = userpasstxt.getText();
                    db_query = String.format("""
                                             INSERT INTO Pharmacist(`PharmacistName`, `Pharmacistpass`)
                                             Values('%s','%s');""",
                        name,pass );
                    Connection conn = Connection2DB.ConneectorDB();
                    Statement s = conn.createStatement();
                    s.executeUpdate(db_query);
                    JOptionPane.showMessageDialog(null,"Submetd!");
                    pharmacyLogin frm = new pharmacyLogin();
                    frm.setVisible(true);
                    this.dispose();

                }
                catch(SQLException sqle){
                    System.out.println(sqle.getMessage());
                }
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Didn't select type"
                ,
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        }
    }//GEN-LAST:event_SumbmetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registr2Pharmacy().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CustomerRB;
    private javax.swing.JRadioButton PharmcistRB;
    private javax.swing.JButton Sumbmetbtn;
    private javax.swing.ButtonGroup UsertypeBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField userNametxt;
    private javax.swing.JTextField userpasstxt;
    // End of variables declaration//GEN-END:variables
}
